
replicaCount: 1

image:
  repository: your-docker-repo/django-app
  tag: latest
  pullPolicy: IfNotPresent

autoscaling:
  enabled: false

env:
  SECRET_KEY: "your-secret-key"
  DEBUG: "False"
  DATABASE_HOST: "postgresql.postgres.cluster.svc.local"
  DATABASE_PORT: "5432"
  DATABASE_USER: "admin"  
  DATABASE_PASSWORD: "cG9zdGdyZXM="  
  DATABASE_NAME: "django"

service:
  port: 8080

ingress:
  enabled: false

volumes:
  - name: secrets-volume
    secret:
      secretName: django-app-secrets
  - name: configmap-volume
    configMap:
      name: django-app-config

livenessProbe:
  httpGet:
    path: /health/
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health/
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

resources:
  requests:
    memory: "128Mi"
    cpu: "200m"
  limits:
    memory: "1024Mi"
    cpu: "1"

nodeSelector: {}
affinity: {}
tolerations: []
