
global:
  postgresql:
    postgresqlUsername: "admin"
    postgresqlPassword: "postgres"
    postgresqlDatabase: "django"
    postgresqlPostgresPassword: "django"
    
persistence:
  enabled: true
  size: 8Gi

service:
  type: ClusterIP
postgresql:
  extraEnvVars:
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
