apiVersion: v1
kind: ConfigMap
metadata:
  name: django-app-config
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
data:
  DATABASE_NAME: {{ .Values.env.DATABASE_NAME | quote }}
  DATABASE_USER: {{ .Values.env.DATABASE_USER | quote }}
  DATABASE_HOST: {{ .Values.env.DATABASE_HOST | quote }}
  DATABASE_PORT: {{ .Values.env.DATABASE_PORT | quote }}
  DEBUG: {{ .Values.env.DEBUG | quote }}
