apiVersion: v1
kind: Secret
metadata:
  name: django-app-secrets
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.env.SECRET_KEY | quote }}
  DATABASE_PASSWORD: {{ .Values.env.DATABASE_PASSWORD | quote }}
